# Generated by Django 2.2.6 on 2020-05-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('0', '10'), ('1', '11'), ('2', '12')], default='-----', max_length=20)),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tên lớp')),
            ],
            options={
                'verbose_name': 'Danh sách lớp',
                'verbose_name_plural': 'Danh sách lớp',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên thời khóa biểu')),
                ('semester', models.CharField(choices=[('0', '1'), ('1', '2')], default='-----', max_length=20, verbose_name='Học kỳ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('last_modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
            ],
            options={
                'verbose_name': 'Danh sách thời khóa biểu',
                'verbose_name_plural': 'Danh sách thời khóa biểu',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên môn học')),
            ],
            options={
                'verbose_name': 'Danh sách môn học',
                'verbose_name_plural': 'Danh sách môn học',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên')),
            ],
            options={
                'verbose_name': 'Danh sách giáo viên',
                'verbose_name_plural': 'Danh sách giáo viên',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Class', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Danh sách Học sinh',
                'verbose_name_plural': 'Danh sách Học sinh',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, null=True, verbose_name='Kết qua')),
                ('type', models.CharField(choices=[('0', "Điểm 15'"), ('1', "Điểm 45'"), ('2', "Điểm học kỳ'"), ('3', "Điểm miệng'")], default='-----', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('last_modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Student', verbose_name='Học sinh')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Danh sách Điểm',
                'verbose_name_plural': 'Danh sách Điểm',
                'ordering': ['student_id', 'subject_id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ghi chú')),
                ('time', models.CharField(choices=[('0', 'Thứ 2'), ('1', 'Thứ 3'), ('2', 'Thứ 4'), ('3', 'Thứ 5'), ('4', 'Thứ 6'), ('5', 'Thứ 7')], default='-----', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('last_modify_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Class', verbose_name='Lớp')),
                ('schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Schedule', verbose_name='Thời khóa biểu')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Subject', verbose_name='Môn học')),
                ('teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Teacher', verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Danh sách buổi học',
                'verbose_name_plural': 'Danh sách buổi học',
                'ordering': ['teacher_id', 'class_id', 'subject_id'],
            },
        ),
    ]
