# Generated by Django 2.2.6 on 2020-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='parts_of_the_day',
            field=models.CharField(choices=[('0', 'Buổi sáng'), ('1', 'Buổi chiều')], default='-----', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.CharField(choices=[('0', 'Tiết 1'), ('1', 'Tiết 2'), ('2', 'Tiết 3'), ('3', 'Tiết 4'), ('4', 'Tiết 5')], default='-----', max_length=20),
        ),
    ]
