# Generated by Django 2.2.6 on 2020-05-12 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200512_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Class', verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Class', verbose_name='Lớp'),
        ),
    ]
