# Generated by Django 2.2.6 on 2020-05-12 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_auto_20200512_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='user_id',
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lớp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lớp'),
        ),
    ]
